---
title: "Tutorial"
output: 
  learnr::tutorial:
    toc_depth: 3
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE,
                      comment="")
tutorial_html_dependency()

child_docs <- dir() %>% 
  str_extract("[0-9]{2}.+[.]Rmd") %>% 
  .[!is.na(.)]
```
```{css, echo = FALSE}
.showcase {
  width: 100%;
  height: 600px;
}
.photo {
  border: 1px solid black;
  border-radius: 50%;
}
.box-person {
  border: 1px solid black;
  padding: 10px;
  margin-top: 10px;
  width: 500px;
}
.box-person::before {
  content: "👋";
  font-size: 25px;
}
.box-person:hover {
 box-shadow: 3px 3px #888888;
 border: 2px solid black;
}

.info-box {
  padding: 12px 24px 12px 30px;
  margin: 2em 2em;
  background-color: rgba(2, 126, 182, 0.3);
  border-left: 6px solid #006DAE;
  position: relative;
}

.info-box::before {
  background-color: #006DAE;
  border-radius: 100%;
  color: #fff;
  content: "\1F4DD";
  font-size: 14px;
  font-weight: 700;
  line-height: 25px;
  position: absolute;
  height: 25px;
  width: 25px;
  text-align: center;
  top: 10px;
  left: -14.5px;
}
```


```{r child=child_docs}
```

